name: Main Release

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      pages: write

    steps:
      - name: Checkout badges branch dedicated to storing badges only
        uses: actions/checkout@v4
        with:
          ref: badges
          path: badges

      - name: Checkout Main Project
        uses: actions/checkout@v4
        with:
          path: main-project

      - name: Checkout gradle-kit
        uses: actions/checkout@v4
        with:
          repository: jonloucks/gradle-kit
          path: gradle-kit

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

      - name: Publish gradle-kit locally
        working-directory: gradle-kit
        run: ./gradlew publishToMavenLocal
        env:
          PROJECT_WORKFLOW: 'utility'

      - name: Build with Gradle
        working-directory: main-project
        run: ./gradlew build jacocoTestReport
        env:
          PROJECT_WORKFLOW: 'main-release'

      - name: Upload JaCoCo report artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: main-project/build/reports/jacoco/test/html/

      - name: Commit and Push the Badge
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update JaCoCo coverage badge'
          add: 'jacoco-badge.svg'
          cwd: badges

      - name: Generate JaCoCo Badge
        id: jacoco
        uses: cicirello/jacoco-badge-generator@v2.11.0
        with:
          coverage-badge-filename: ${{ env.BRANCH_NAME }}-coverage.svg
          badges-directory: badges
          jacoco-csv-file: main-project/build/reports/jacoco/test/jacocoTestReport.csv
        env:
          BRANCH_NAME: ${{ github.ref_name }}

      - name: Commit and Push the Badge
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: 'Update JaCoCo coverage badge'
          add: '*.svg'
          cwd: badges

      - name: Log coverage percentage
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Publish to GitHub Packages
        working-directory: main-project
        run: ./gradlew publish createPublisherBundle uploadPublisherBundle
        env:
          PROJECT_WORKFLOW: 'main-release'
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OSSRH_GPG_SECRET_KEY: ${{ secrets.OSSRH_GPG_SECRET_KEY }}
          OSSRH_GPG_SECRET_KEY_PASSWORD: ${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}

